Adjust the counting method of words to adapt to Chinese, Japanese, Korean, etc.
shadeMe/Fuz-Ro-D-oh-64 pull request #6
Opened 2022-12-23 01:43 UTC by zoollcar

Adjust the counting method of words to accommodate languages without spaces between words, such as Chinese, Japanese, and Korean.

Chinese tested, Japanese and Korean theory available, not tested.

Does not affect the normal use of English.

Implement:

The first 128 code points (ASCII) need one byte. The next 1,920 code points need two bytes to encode, which covers the remainder of almost all Latin-script alphabets, and also IPA extensions, Greek, Cyrillic, Coptic, Armenian, Hebrew, Arabic, Syriac, Thaana and N'Ko alphabets, as well as Combining Diacritical Marks. Three bytes are needed for the rest of the Basic Multilingual Plane, which contains virtually all code points in common use,[16] including most Chinese, Japanese and Korean characters. Four bytes are needed for code points in the other planes of Unicode, which include less common CJK characters, various historic scripts, mathematical symbols, and emoji (pictographic symbols). ---wikipedia

Does not affect one byte code and two byte code, For counting 3 byte code and 4 byte code, configure word segmentation according to `WideCharacterPerWord` in the ini file.

2022-12-23 01:46 UTC, zoollcar commented
Precompiled:

[Fuz Ro D'oh-15109-2-3.zip](https://github.com/shadeMe/Fuz-Ro-D-oh-64/files/10291416/Fuz.Ro.D.oh-15109-2-3.zip)

2022-12-27 12:28 UTC, shadeMe requested changes
Thanks for the PR! Just a couple of minor changes.

On what languages was this addition tested?

2022-12-27 12:28 UTC, shadeMe commented on Hooks.cpp
> +					}
```suggestion
						CharOver = 3; // a 4 wide-character, 3 bytes left
```

2022-12-27 12:28 UTC, shadeMe commented on Hooks.cpp
> +					}
```suggestion
					else
						CharOver = 2; // a 3 wide-character, 2 bytes left
```

2022-12-27 12:28 UTC, shadeMe commented on Hooks.cpp
> +				}
```suggestion
				else
					WordCount += (ch == ' ');
```

2022-12-28 02:07 UTC, zoollcar commented
I tested Chinese on v1.6.640, no other languages tested.

I can technically test Japanese Korean, maybe later, but I don't know those languages, a native test would be better.

2022-12-28 09:56 UTC, shadeMe approved these changes

2022-12-28 09:57 UTC, merged

2022-12-28 11:52 UTC, shadeMe commented
Thanks again. I don't have an ETA for the next public release, but I'll try to get it out sooner rather than later.